FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY TestMariaDBApp/TestMariaDBApp.csproj ./TestMariaDBApp/
RUN dotnet restore TestMariaDBApp/TestMariaDBApp.csproj

COPY TestMariaDBApp/ ./TestMariaDBApp/

RUN dotnet publish TestMariaDBApp/TestMariaDBApp.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "TestMariaDBApp.dll"]
